-- Schema for MyBatis version of backend (previously auto-generated by Hibernate ddl-auto=update)
-- Statements are idempotent so this file can safely run on every application startup
-- (spring.sql.init.mode=always in application.properties).

CREATE TABLE IF NOT EXISTS tbl_member (
    email    VARCHAR(100) NOT NULL,
    pw       VARCHAR(100) NOT NULL,
    nickname VARCHAR(50)  NOT NULL,
    social   BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS tbl_member_role (
    member_email VARCHAR(100) NOT NULL,
    role_name    VARCHAR(20)  NOT NULL,
    CONSTRAINT fk_member_role_email FOREIGN KEY (member_email) REFERENCES tbl_member (email)
);
